apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whatismyip.fullname" . }}
  labels:
    {{- include "whatismyip.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "whatismyip.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.PodAnnotations }}
      {{- with .Values.PodAnnotations}}
      annotations:
      {{- toYaml . | nindent 8}}
      {{- end }}
      {{- end }} 
      labels:
        {{- include "whatismyip.labels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecrets }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
        - name: {{ include "whatismyip.name" . }} 
          {{- if .Values.image.registry }}
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag}}
          {{- else}}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}