apiVersion: v1
kind: Service
metadata:
  name: {{ include "whatismyip.fullname" . }}
  labels:
    {{- include "whatismyip.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  {{- with .Values.service.annotations}}
  annotations:
  {{- toYaml . | nindent 8}}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
  {{- include "whatismyip.selectorLabels" . | nindent 4 }}