image:
  registry: 
  repository: keeperdekel/whatismyip
  tag: 0.0.2
  pullPolicy: "IfNotPresent"
  pullSecrets: {}
  #  - secretname 
nameOverride: "coolname"
replicaCount: 1 
PodAnnotations: {}
commonlabels: 
  - environment: dev
resources:
  requests:
    memory: "128Mi"
    cpu: "128m"
  limits:
    memory: "1024Mi"
    cpu: "512m"
service:
  type: "ClusterIP"
  port: 5000
  annotations: {}

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 10
livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 20
  failureThreshold: 10

ingress: 
  enabled: true
  host: "sisence.dekel.com"

nginx-ingress:
  controller:
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'false'
        service.beta.kubernetes.io/aws-load-balancer-type: nlb